// super-ui/lib/web/components/screens/login.vue
<template>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="form">
        <div class="form-group">
          <h2>Sign In</h2>
        </div>

        <div class="form-group">
          <label>Empire Name</label>
          <input type="text" class="form-control" placeholder="Empire Name" v-model="empire" />
        </div>

        <div class="form-group">
          <label>Password</label>
          <input type="password" class="form-control" v-model="password" placeholder="Password" />
        </div>

        <div class="form-group">
          <label>Server</label>
          <select class="form-control" v-model="server">
            <option value="us1">US1</option>
            <option value="pt">Public Test</option>
            <option value="http://localhost:8080">Local Server</option>
          </select>
        </div>

        <div class="form-group">
          <button class="btn btn-lg btn-primary btn-block" @click="handleLogin">Sign in</button>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import _ from 'lodash';
import * as bootstrapper from '../../bootstrapper';
import ConfigStore from '../../stores/config';

export default {
  data() {
    return {
      empire: ConfigStore.get().empire,
      password: ConfigStore.get().password,
      server: ConfigStore.get().server,
    };
  },

  methods: {
    handleLogin() {
      console.log(`Logging into ${this.server} with ${this.empire}`);
      bootstrapper.freshLogin({
        empire: this.empire,
        password: this.password,
        server: this.server,
      });
    },
  },
};
</script>

// super-ui/lib/web/components/screens/login.jsx
import React from 'react';
import Reflux from 'reflux';
import _ from 'lodash';
let $ = window.jQuery;

import * as bootstrapper from '../../bootstrapper';

import ConfigStore from '../../stores/config';

let LoginScreen = React.createClass({
  mixins: [Reflux.connect(ConfigStore, 'config')],

  componentDidMount() {
    let handleReturn = (e) => {
      if (e.keyCode === 13) {
        this.handleLogin();
      }
    };

    let elements = [this.refs.empire, this.refs.password];

    _.each(elements, (el) => {
      $(el).off().on('keypress', handleReturn);
    });
  },

  handleLogin() {
    bootstrapper.freshLogin({
      empire: this.refs.empire.value,
      password: this.refs.password.value,
      server: this.refs.server.value,
    });
  },

  render() {
    return (
      <div className='row'>
        <div className='col-md-4 col-md-offset-4'>
          <div className='form'>
            <div className='form-group'>
              <h2>Sign In</h2>
            </div>

            <div className='form-group'>
              <input
                type='text'
                ref='empire'
                className='form-control'
                placeholder='Empire Name'
                defaultValue={this.state.config.empire}
              ></input>

              <input
                type='password'
                ref='password'
                className='form-control'
                defaultValue={this.state.config.password}
                placeholder='Password'
              ></input>
            </div>

            <div className='form-group'>
              <select className='form-control' ref='server'>
                <option value='us1'>US1</option>
                <option value='pt'>Public Test</option>
                <option value='http://localhost:8080'>Local Server</option>
              </select>
            </div>

            <div className='form-group'>
              <button className='btn btn-lg btn-primary btn-block' onClick={this.handleLogin}>
                Sign in
              </button>
            </div>
          </div>
        </div>
      </div>
    );
  },
});

export default LoginScreen;
