// super-ui/lib/web/components/screens/task-selection.jsx
import React from 'react';
import _ from 'lodash';

import * as taskIndex from '../../../../lib/tasks';
const tasks = taskIndex.getTasksForPlatform('web');

import RunnerActions from '../../actions/runner';

let TaskSelectionScreen = React.createClass({
  handleTaskSelect(event) {
    RunnerActions.setSelectedTask(event.target.attributes.value.nodeValue);
  },

  render() {
    return (
      <div className='row'>
        <div className='col-md-4 col-md-offset-4'>
          <h1 className='center-text'>Select a Task</h1>

          <ul>
            {_.map(tasks, (task) => {
              return (
                <li
                  key={task.name}
                  style={{
                    cursor: 'pointer',
                  }}
                >
                  <a value={task.name} title={task.description} onClick={this.handleTaskSelect}>
                    {task.title}
                  </a>
                </li>
              );
            })}
          </ul>
        </div>
      </div>
    );
  },
});

export default TaskSelectionScreen;

// super-ui/lib/web/components/screens/task-selection.vue
<template>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <h1 class="center-text">Select a Task</h1>

      <ul>
        <li v-for="task in tasks" style="cursor: pointer">
          <router-link :to="'/task-configuration/' + task.name" :title="task.description">{{
            task.title
          }}</router-link>
        </li>
      </ul>
    </div>
  </div>
</template>

<script>
import * as taskIndex from '../../../../lib/tasks';

export default {
  data() {
    return {
      tasks: taskIndex.getTasksForPlatform('web'),
    };
  },
};
</script>
