// super-ui/lib/web/components/task-configs/halls-cost.vue
<template>
  <div class="form">
    <div class="form-group">
      <label>Start</label>
      <select class="form-control" name="start" v-model="start">
        <option v-for="level in levels" :value="level">{{ level }}</option>
      </select>
    </div>

    <div class="form-group">
      <label>End</label>
      <select class="form-control" name="end" v-model="end">
        <option v-for="level in levels" :value="level">{{ level }}</option>
      </select>
    </div>
  </div>
</template>

<script>
import _ from 'lodash';

export default {
  data() {
    return {
      levels: _.range(1, 31),
      start: 1,
      end: 30,
    };
  },
};
</script>

// super-ui/lib/web/components/task-configs/halls-cost.jsx
import React from 'react';
import _ from 'lodash';

import util from '../../../util';

let HallsCost = React.createClass({
  getOptions() {
    return {
      start: util.int(this.refs.startList.value),
      end: util.int(this.refs.endList.value),
    };
  },

  render() {
    let list = _.chain(_.range(1, 31))
      .map((num) => {
        return (
          <option value={num} key={num}>
            {num}
          </option>
        );
      })
      .value();

    return (
      <div className='form'>
        <div className='form-group'>
          <label>Start</label>
          <select className='form-control' ref='startList'>
            {list}
          </select>
        </div>
        <div className='form-group'>
          <label>End</label>
          <select className='form-control' defaultValue={30} ref='endList'>
            {list}
          </select>
        </div>
      </div>
    );
  },
});

export default HallsCost;
