// super-ui/lib/web/components/task-configs/push-buildings-up.vue
<template>
  <div class="form">
    <div class="form-group">
      <ColonyList name="planet" label="Select Planet" all />
    </div>

    <Checkbox name="loop" label="Loop" description="Wait for buildings to upgrade and go agin" />

    <DryRunCheckbox name="dryRun" />
  </div>
</template>

<script>
import ColonyList from './helpers/colony-list.vue';
import Checkbox from './helpers/checkbox.vue';
import DryRunCheckbox from './helpers/dry-run-checkbox.vue';

export default {
  components: { ColonyList, Checkbox, DryRunCheckbox },
};
</script>

// super-ui/lib/web/components/task-configs/push-buildings-up.jsx
import React from 'react';

import ColonyList from './helpers/colony-list';
import DryRunCheckbox from './helpers/dry-run-checkbox';
import Checkbox from './helpers/checkbox';

let PushBuildingsUpConfig = React.createClass({
  getOptions() {
    return {
      planet: this.refs.list.getSelected().name,
      dryRun: this.refs.dryRun.isChecked(),
      loop: this.refs.loop.isChecked(),
    };
  },

  render() {
    return (
      <div className='form'>
        <div className='form-group'>
          <ColonyList ref='list' />
        </div>

        <Checkbox ref='loop' label='Loop' description='Wait for buildings to upgrade and go agin' />

        <DryRunCheckbox ref='dryRun' />
      </div>
    );
  },
});

export default PushBuildingsUpConfig;
