// super-ui/lib/web/components/task-configs/push-glyphs.jsx
import React from 'react';

import ColonyList from './helpers/colony-list';

let PushGlyphsConfig = React.createClass({
  getOptions() {
    return {
      from: this.refs.from.getSelected().name,
      to: this.refs.to.getSelected().name,
    };
  },

  render() {
    return (
      <div className='form'>
        <div className='form-group'>
          <ColonyList label='From' ref='from' />
        </div>

        <div className='form-group'>
          <ColonyList label='To' ref='to' all={false} />
        </div>
      </div>
    );
  },
});

export default PushGlyphsConfig;

// super-ui/lib/web/components/task-configs/push-glyphs.vue
<template>
  <div class="form">
    <div class="form-group">
      <ColonyList name="from" label="From" all />
    </div>

    <div class="form-group">
      <ColonyList name="to" label="To" />
    </div>
  </div>
</template>

<script>
import ColonyList from './helpers/colony-list.vue';

export default {
  components: { ColonyList },
};
</script>
