// super-ui/lib/web/components/task-configs/spy-trainer.vue
<template>
  <div class="form">
    <div class="form-group">
      <ColonyList name="planet" label="Planet" all />
    </div>

    <div class="form-group">
      <DryRunCheckbox name="dryRun" />
    </div>
  </div>
</template>

<script>
import ColonyList from './helpers/colony-list.vue';
import DryRunCheckbox from './helpers/dry-run-checkbox.vue';

export default {
  components: { ColonyList, DryRunCheckbox },
};
</script>

// super-ui/lib/web/components/task-configs/spy-trainer.jsx
import React from 'react';

import Captcha from './helpers/captcha';
import ColonyList from './helpers/colony-list';
import DryRunCheckbox from './helpers/dry-run-checkbox';

let SpyTrainerConfig = React.createClass({
  getOptions() {
    return {
      planet: this.refs.list.getSelected().name,
      dryRun: this.refs.dryRun.isChecked(),
    };
  },

  render() {
    return (
      <div className='form'>
        <div className='form-group'>
          <ColonyList ref='list' />
        </div>

        <DryRunCheckbox ref='dryRun'>
          <Captcha />
        </DryRunCheckbox>
      </div>
    );
  },
});

export default SpyTrainerConfig;
