// super-ui/lib/web/components/task-configs/helpers/checkbox.vue
<template>
  <div>
    <div class="form-group">
      <div class="checkbox">
        <label> <input type="checkbox" v-model="checked" :name="name" /> {{ label }}</label>
        <span class="help-block">{{ description }}</span>
      </div>
    </div>

    <div class="form-group" v-if="!checked">
      <slot></slot>
    </div>
  </div>
</template>

<script>
export default {
  props: ['label', 'description', 'name'],

  data() {
    return {
      checked: false,
    };
  },
};
</script>

// super-ui/lib/web/components/task-configs/helpers/checkbox.jsx
import React from 'react';

let Checkbox = React.createClass({
  propTypes: {
    label: React.PropTypes.string.isRequired,
    description: React.PropTypes.string.isRequired,
    children: React.PropTypes.oneOfType([
      React.PropTypes.element,
      React.PropTypes.node,
      React.PropTypes.undefined,
    ]),
  },

  getDefaultProps() {
    return {
      label: '',
      description: '',
      children: '',
    };
  },

  getInitialState() {
    return {
      checked: false,
    };
  },

  toggle() {
    this.setState({
      checked: !this.state.checked,
    });
  },

  isChecked() {
    return this.state.checked;
  },

  getOptionalContent() {
    if (!this.state.checked && this.props.children) {
      return <div className='form-group'>{this.props.children}</div>;
    } else {
      return '';
    }
  },

  render() {
    return (
      <div>
        <div className='form-group'>
          <div className='checkbox'>
            <label>
              <input type='checkbox' checked={this.state.checked} onChange={this.toggle}></input>
              {this.props.label}
            </label>
            <span className='help-block'>{this.props.description}</span>
          </div>
        </div>

        {this.getOptionalContent()}
      </div>
    );
  },
});

export default Checkbox;
