// super-ui/lib/web/components/task-configs/helpers/colony-list.vue
<template>
  <List :label="label" :name="name" :list="bodies" />
</template>

<script>
import _ from 'lodash';
import List from './list.vue';
import EmpireStore from '../../../stores/empire';

export default {
  props: {
    label: String,
    name: String,
    all: Boolean,
  },

  components: { List },

  computed: {
    bodies() {
      const bodies = [];

      if (this.all) {
        bodies.push({ name: 'All', value: 'all' });
      }

      if (EmpireStore?.data?.bodies?.colonies) {
        _.each(EmpireStore.data.bodies.colonies, ({ name }) => {
          bodies.push({ name, value: name });
        });
      }

      return bodies;
    },
  },
};
</script>

// super-ui/lib/web/components/task-configs/helpers/colony-list.jsx
import React from 'react';
import Reflux from 'reflux';

import BodyList from './body-list';

import EmpireStore from '../../../stores/empire';

let ColonyList = React.createClass({
  mixins: [Reflux.connect(EmpireStore, 'empire')],

  propTypes: {
    all: React.PropTypes.bool,
    label: React.PropTypes.string,
  },

  getDefaultProps() {
    return {
      all: true,
      label: 'Colony',
    };
  },

  getSelected() {
    return this.refs.list.getSelected();
  },

  render() {
    return (
      <BodyList
        bodies={this.state.empire.colonies}
        all={this.props.all}
        label={this.props.label}
        ref='list'
      />
    );
  },
});

export default ColonyList;
