// super-ui/lib/web/components/task-configs/helpers/dry-run-checkbox.jsx
import React from 'react';

import Checkbox from './checkbox';

let DryRunCheckbox = React.createClass({
  propTypes: {
    children: React.PropTypes.oneOfType([
      React.PropTypes.element,
      React.PropTypes.node,
      React.PropTypes.undefined,
    ]),
  },

  isChecked() {
    return this.refs.checkbox.isChecked();
  },

  render() {
    return (
      <div>
        <Checkbox
          label='Dry Run'
          description='Runs the task and shows what would happen without actually changing anything'
          ref='checkbox'
        >
          {this.props.children}
        </Checkbox>
      </div>
    );
  },
});

export default DryRunCheckbox;

// super-ui/lib/web/components/task-configs/helpers/dry-run-checkbox.vue
<template>
  <div>
    <Checkbox
      label="Dry Run"
      description="Runs the task and shows what would happen without actually changing anything"
      :name="name"
    >
      <slot></slot>
    </Checkbox>
  </div>
</template>

<script>
import Checkbox from './checkbox.vue';
export default {
  props: ['name'],
  components: { Checkbox },
};
</script>
