// super-ui/lib/web/components/menu/nav-bar.vue
<template>
  <div class="navbar navbar-default">
    <div class="navbar-header">
      <router-link :to="this.isAuthenticated ? '/task-selection' : '/login'" class="navbar-brand">
        TLE Power UI
      </router-link>
    </div>

    <ul class="nav navbar-nav navbar-left">
      <li v-if="isAuthenticated">
        <router-link to="/task-selection">Tasks</router-link>
      </li>
      <li>
        <a target="_blank" href="https://1vasari.github.io/le-serf-docs/">Documentation</a>
      </li>
      <li>
        <router-link to="/about">About</router-link>
      </li>
    </ul>

    <p class="navbar-text navbar-right" style="margin-right: 15px">
      <span v-if="isAuthenticated">
        Logged in as {{ this.empire.name }} |
        <span>
          <a @click="logout" style="cursor: pointer">Log out</a>
        </span>
      </span>
      <span v-if="!isAuthenticated">
        Not logged in | <router-link to="/login">Login</router-link>
      </span>
    </p>
  </div>
</template>

<script>
import EmpireStore from '../../stores/empire';
import * as App from '../../app';

export default {
  data() {
    return {
      empire: EmpireStore.data,
    };
  },

  methods: {
    onBrandClick() {
      if (this.empire.name) {
        App.navigate('/task-selection');
      } else {
        App.navigate('/login');
      }
    },

    logout() {
      EmpireStore.logout();
    },
  },

  computed: {
    isAuthenticated() {
      return !!this.empire.name;
    },
  },
};
</script>

// super-ui/lib/web/components/menu/nav-bar.jsx
import React from 'react';
import Reflux from 'reflux';

import { Link } from 'react-router';

import WindowActions from '../../actions/window';
import EmpireActions from '../../actions/empire';

import EmpireStore from '../../stores/empire';

let BrandSection = React.createClass({
  handleClick(e) {
    e.preventDefault();

    if (EmpireStore.getData().name) {
      WindowActions.navigate('/task-selection');
    } else {
      WindowActions.navigate('/login');
    }
  },

  render() {
    return (
      <div className='navbar-header'>
        <a className='navbar-brand' href='#' onClick={this.handleClick}>
          Le Serf
        </a>
      </div>
    );
  },
});

let LinksSection = React.createClass({
  render() {
    return (
      <ul className='nav navbar-nav navbar-left'>
        <li>
          <Link to='/task-selection'>Tasks</Link>
        </li>
        <li>
          <Link to='/output'>Output</Link>
        </li>
        <li>
          <a target='_blank' href='http://1vasari.github.io/le-serf-docs/'>
            Documentation
          </a>
        </li>
        <li>
          <Link to='/about'>About</Link>
        </li>
      </ul>
    );
  },
});

let EmpireSection = React.createClass({
  mixins: [Reflux.connect(EmpireStore, 'empire')],

  logout() {
    EmpireActions.logout();
  },

  render() {
    return (
      <p className='navbar-text navbar-right' style={{ marginRight: 15 }}>
        {this.state.empire.name ? (
          <span>
            Logged in as {this.state.empire.name} |{' '}
            <span>
              <a
                onClick={this.logout}
                style={{
                  cursor: 'pointer',
                }}
              >
                Log out
              </a>
            </span>
          </span>
        ) : (
          <span>
            Not logged in | <Link to='/login'>Login</Link>
          </span>
        )}
      </p>
    );
  },
});

let NavBar = React.createClass({
  render() {
    return (
      <div className='navbar navbar-default'>
        <BrandSection />
        <LinksSection />
        <EmpireSection />
      </div>
    );
  },
});

export default NavBar;
